name: source_maps_dumper
description: A CLI Script for dumping source maps from HAR files.
version: 1.1.1

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
